// src/main.js
import "@material/web/icon/icon.js"
import "@material/web/iconbutton/icon-button.js"
import '@material/web/button/filled-button.js';
import '@material/web/button/outlined-button.js';
import '@material/web/checkbox/checkbox.js';
import '@material/web/button/text-button.js'
import '@material/web/tabs/tabs.js'
import "@material/web/tabs/primary-tab.js"
import "@material/web/tabs/secondary-tab.js"
import "@material/web/fab/fab.js"
import "@material/web/fab/branded-fab.js"
import "@material/web/ripple/ripple.js"