import 'mdui/components/fab.js';
import 'mdui/components/card.js';
import 'mdui/components/tabs.js';
import 'mdui/components/tab.js';
import 'mdui/components/tab-panel.js';
import 'mdui/components/navigation-bar.js';
import 'mdui/components/navigation-bar-item.js';
import 'mdui/components/navigation-rail.js';
import 'mdui/components/navigation-rail-item.js';
import 'mdui/components/dialog.js';
import 'mdui/components/button.js';
import 'mdui/components/snackbar.js';
import { setColorScheme } from 'mdui/functions/setColorScheme.js';
setColorScheme('#ff8c00');